name: Producao Deployment

on:
  push:
    branches:
      - "l3sistemas"

jobs:
  build-producao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: yarn
      - run: yarn quasar build

      - name: Copy Files to Server (Producao)
        uses: appleboy/scp-action@master
        with:
          host: '64.23.181.219'
          username: ${{ vars.USERNAME_L3 }}
          key: ${{ secrets.SSH_KEY_L3 }}
          port: ${{ vars.PORT_L3 }}
          source: "./dist/spa"
          target: "/var/www/web/public_html"

      - name: Deploy (Develop)
        uses: appleboy/ssh-action@master
        with:
          host: '64.23.181.219'
          username: ${{ vars.USERNAME_L3 }}
          key: ${{ secrets.SSH_KEY_L3 }}
          port: ${{ vars.PORT_L3 }}
          script: |
            cd /var/www/web/public_html
            cp -r -v dist/spa/* /var/www/web/public_html
