# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Build CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: yarn
      - run: yarn quasar build

      # - name: 📂 Sync files
      #   uses: SamKirkland/FTP-Deploy-Action@4.3.2
      #   with:
      #     server: "cajueiro.cajutec.com.br"
      #     username: ${{ vars.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     port: 22
      #     local-dir: "./dist/spa/"
      #     server-dir: "cajueiro.cajutec.com.br/web/"

      - name: Copy Files to Server (Producao)
        uses: appleboy/scp-action@master
        with:
          host: 'cajueiro.cajutec.com.br'
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: './dist/spa/'
          target: 'cajueiro.cajutec.com.br/web/'

      - name: Deploy (Develop)
        uses: appleboy/ssh-action@master
        with:
          host: 'cajueiro.cajutec.com.br'
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            cd /home/wwcaju/cajueiro.cajutec.com.br/web
            cp -r -v dist/spa/* /home/wwcaju/cajueiro.cajutec.com.br/web
